mainpage/urls.py
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.urls import path
from django.views.generic import TemplateView

from . import views


app_name = 'mainpage'

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html'), name='index'),
    path('CV/', views.GenerateCV.as_view(), name='cv'),
]

urlpatterns += staticfiles_urlpatterns()

payment/urls.py
from django.urls import path

from .  import  views


app_name = 'payment'

urlpatterns = [
    path('', views.PaymentView.as_view(), name='index'),
    path('free_pdf/', views.GenerateFreePdf.as_view(), name='free_pdf'),
    path('callback/', views.PaymentCallbackView.as_view(), name='payment_callback'),
]

personal/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('payment/', include('payment.urls')),
    path('', include('mainpage.urls')),
]

mainpage/models.py
from django.db import models

# Create your models here.

mainpage/views.py
from django.shortcuts import render
from django.views.generic import View
from payment.utils import *
from .conf import *


class GenerateCV(View):
    def post(self, request):
        return renderPdf(CV_PATH, "CV", "inline")
    def get(self, request):
        return renderPdf(CV_PATH, "CV", "inline")

payment/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.contrib import messages
from django.views.generic import View
from django.http import HttpResponseBadRequest, HttpResponseForbidden
from django.views.decorators.csrf import csrf_exempt
from django.utils.decorators import method_decorator
import random
import json

# import conf
from .conf import *

# Soap Client
from zeep import Client
from .utils import *

class PaymentView(View):
    template_name = 'payment.html'
    messages = {
        "invalid_amount": {
            "level": messages.ERROR,
            "text": "Invalid Amount"
        },
        "get_token_fail": {
            "level": messages.ERROR,
            "text": "Get Token Failed : %s"
        },
    }

    def get(self, request):
        return render(request, self.template_name, {})

    def post(self, request):

        # amount = request.POST.get('amount')
        amount = AMOUNT
        order_id = random.random()

        # store in session
        # request.session['amount'] = amount
        # request.session['order_id'] = order_id

        if amount:
            client = Client('https://api.nextpay.org/gateway/token.wsdl')
            result = client.service.TokenGenerator(
                API_KEY,
                order_id,
                amount,
                request.build_absolute_uri(reverse('payment:payment_callback')),
            )

            if result.code != -1:
                messages.add_message(
                    self.request,
                    self.messages["get_token_fail"]["level"],
                    self.messages["get_token_fail"]["text"] % result.code
                )
            else:
                return redirect('https://api.nextpay.org/gateway/payment/%s' % result.trans_id)

        else:
            messages.add_message(
                self.request,
                self.messages["invalid_amount"]["level"],
                self.messages["invalid_amount"]["text"]
            )

        return redirect(self.get_fail_url())

    def get_fail_url(self):
        return str(reverse_lazy('payment'))

    def get_success_url(self):
        return str(reverse_lazy('payment'))


class PaymentCallbackView(View):
    template_name = 'callback.html'

    @method_decorator(csrf_exempt)
    def dispatch(self, request, *args, **kwargs):
        return super(PaymentCallbackView, self).dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, {})

    def post(self, request):

        trans_id = request.POST.get('trans_id')
        order_id = request.POST.get('order_id')
        amount = AMOUNT

        print(f'order_id: {order_id}, trans_id: {trans_id}')

        # if order_id != request.session.get('order_id'):
        #     return HttpResponseForbidden()

        if trans_id and order_id and amount:
            client = Client('https://api.nextpay.org/gateway/verify.wsdl')
            result = client.service.PaymentVerification(
                API_KEY,
                order_id,
                amount,
                trans_id,
            )

            # card = result['card_holder']
            resultCode = result['code']
            if resultCode == 0:
                return renderPdf(NOT_FREE_PDF_PATH, "Summary", "inline")
            else:
                return render(request, self.template_name)

            # if result == 0 then success payment
            # return render(request, self.template_name, {
            #     'card': card,
            #     'result_code': resultCode,
            #     'trans_id': trans_id
            # })

        else:
            return HttpResponseBadRequest()


class GenerateFreePdf(View):
    # template_name = 'payment.html'

    def post(self, request):
        return renderPdf(FREE_PDF_PATH, "About the course", "attachment")
    def get(self, request):
        return renderPdf(FREE_PDF_PATH, "About the course", "attachment")

payment/templates/callback.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title> Payment Result: </title>
</head>
<body>
<div style="text-align: center">
    {% if result_code == 0 %}
     <h2>Success Payment</h2>
    {% else %}
    <h2>Fail Payment</h2>
    {% endif %}
<p>Payment Result : {{ result_code }}</p>
<p> Card: {{ card }} </p>
<p>Transaction ID : {{ trans_id }}</p>
</div>
</body>
</html>

payment/templates/payment.html
{% extends 'baseTemplate.html' %}

{% block content %}
<div>
    {% if messages %}
        <div style="text-align: center">
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
        </div>
    {% endif %}
    <div style="text-align: center">
        <p> In this episode of college I passed an useful course about information technology<br>
            My dear teacher was <a href="http://nekoo.ir" target="_blank"> <b> Dr Hashemi nekoo </b> </a> .<br>
            I wrote summary of all things that I learned from this course, and you can see that via this links:
        </p>
        <div>
            <form action="{% url "payment:index" %}" method="post">
                {% csrf_token %}
                <input type="submit" value="summary(payment required)">
            </form>

            <form action="{% url 'payment:free_pdf' %}" method="post">
                {% csrf_token %}
                <input type="submit" value="about the course(Free)">
            </form>
        </div>

    </div>
</div>
{% endblock %}

templates/baseTemplate.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1" charset="UTF-8">
    <title> Ali khoshtinat </title>
    <link rel="stylesheet" href="{% static 'homepage.css' %}">
</head>
<body>

    <div class="parallax" >
        <div>
            <img src="{% static 'myPicResized.jpg' %}" class="firstImg">
            <h1 class="textUnderFirstImg"> Ali khoshtinat </h1>

        </div>
    </div>
    {% block aboutMeTitle %}
    {% endblock %}

    <div class="clearfix">
        {% block content %}

        {% endblock %}

    </div>
    <div class="parallax">
        <div class="textUnderFirstImg" style="padding-bottom: 1%;">
            <p>
                Social
            </p>
        </div>
        <div class="social">
            <a href="https://github.com/tehis" style="max-width: 10%;" target="_blank" >
                <img src="{% static 'github.png' %}" style="max-width: 100%;" >
            </a>
            <a href="mailto:tehis99@gmail.com" style="max-width: 10%;" target="_blank">
                <img src="{% static 'gmail.png' %}" style="max-width: 100%;" alt="gmail">
            </a>
            <a href="https://www.instagram.com/ali_khoshtinattt/" style="max-width: 10%;" target="_blank">
                <img src="{% static 'instagram.png' %}" style="max-width: 100%;">
            </a>
        </div>
    </div>

</body>
</html>

templates/index.html
{% extends 'baseTemplate.html' %}


{% load static from staticfiles %}

{% block aboutMeTitle %}
    <div style="text-align: center; margin-top: 3%;">
        <h1> About Me </h1>
        <p style="color: dimgrey;"> Here are some things that you should know about me. </p>
    </div>
{% endblock %}

{% block content %}
        <p style="font-size: 150vw;"><img src="{% static 'myPic2.jpg' %}" class="myImg" alt="Ali khoshtinat pic">
            <p style="padding-right: 10%; padding-left: 20px;">
                Hi guys :) <br>
                Im <b> Ali khoshtinat </b>.  I was born in Gorgan and then I moved to Tehran,
                Now I study <b> computer enginneering </b> at the <b>University of Tehran</b>. <br>
                I love to code and create useful things for people. <br>
                I also love software design and between technologies I love backend development. <br>
                In my spare time I like to travel and watch movie and gain new skills! <br>
                You can take a look at my <a href="{% url 'mainpage:cv' %}"> CV </a> for more information.
            </p>
            <p style="padding-right: 10%; padding-left: 20px;"> In this episode of college I passed an useful course aboute <b> IT </b>. <br>
                And I provide a summary of it, to watch that click this link.
            </p>
            <a href="{% url 'payment:index' %}"> Read About <b> IT </b> </a>
        </p>
{% endblock %}